### PR TITLE
MainActivity.java

### PR DESCRIPTION
**Pull request by gsetia4022**
Checking Pull Request, How it works

### CODE REVIEW

**Review by gsetia4021 — COMMENTED** [review]
Are you new to Git. So just doing test?

**Comment by gsetia4022** [comment]
Yes

**Comment by gsetia4021** [comment]
Ok Got you !! so you want me to accept your pull request and merge in my code.As there would not be any problem to merge your code.

**Comment by gsetia4022** [comment]
ok

**Pull request merged**
